# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    npm install
    yarn install
    yarn docs:build

- task: AzureRMWebAppDeployment@4
  displayName: Azure App Service Deploy
  inputs:
    WebAppType: Web App On Windows
    ConnectedServiceName: $(azureSubscriptionEndpoint)
    WebAppName: $(WebAppName)
