# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

- script: |
    npm install
    yarn install
    yarn docs:build

- task: AzureCLI@1
  inputs:
    azureSubscription: btwebb_msdn
    workingDirectory: .vuepress/dist
    scriptLocation: inlineScript
    inlineScript: |
      az extension add --name webapp
      az webapp up --location eastus2 --name hello-vuepress